### ISSUE TITLE
docker image cannot run

### ISSUE THREAD

**Issue by yg7001** [arturoeanton/go-notebook#2]
> docker run -it --name gophernotes --rm  -p 1323:1323   arturoeanton/go-notebook

// debug: running "go get gonum.org/v1/plot" ...
go get: module gonum.org/v1/plot: Get "https://proxy.golang.org/gonum.org/v1/plot/@v/list": dial tcp 172.217.163.49:443: i/o timeout
panic: error loading package "gonum.org/v1/plot" metadata: error executing "/usr/local/go/bin/go get gonum.org/v1/plot" in directory "/go/src/gomacro.imports/gonum.org/v1/plot": exit status 1

goroutine 1 [running]:
github.com/cosmos72/gomacro/fast.(*Comp).ImportPackage(...)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/import.go:138
github.com/cosmos72/gomacro/fast.(*Comp).Import(0xc00003c0c0, 0x1aaf000, 0xc000406900)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/import.go:188 +0x3b3
github.com/cosmos72/gomacro/fast.(*Comp).compileNode(0xc00003c0c0, 0x1aa6ed8, 0xc000406900, 0x4, 0x30)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/compile.go:427 +0x21b
github.com/cosmos72/gomacro/fast.(*Comp).compileDecl(0xc00003c0c0, 0xc0001f2550, 0x0)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/compile.go:387 +0x4af
github.com/cosmos72/gomacro/fast.(*Comp).Compile(0xc00003c0c0, 0x1ab91f8, 0xc00026bde8, 0x1ab91f8)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/compile.go:347 +0x1df
github.com/cosmos72/gomacro/fast.(*Interp).CompileAst(0xc000284d50, 0x1ab91f8, 0xc00026bde8, 0x1ab91f8)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/repl.go:94 +0x1a5
github.com/cosmos72/gomacro/fast.(*Interp).Compile(0xc000284d50, 0xc0001f6000, 0x181, 0x181)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/repl.go:74 +0x65
github.com/cosmos72/gomacro/fast.(*Interp).Eval(0xc000284d50, 0xc0001f6000, 0x181, 0x181, 0x0, 0x0, 0x4, 0xc0002068c0, 0x0)
        /go/pkg/mod/github.com/cosmos72/gomacro@v0.0.0-20210624153544-b4935e406a41/fast/interpreter.go:262 +0x45
main.main()
        /app/main.go:226 +0x2fc

**Comment by arturoeanton** [comment]
can you compile new version with this command 
docker build .  -t arturoeanton/go-notebook
